const FIRESTORE_KEY_PRIMERA_REUNION = 'primera-reunion';
const FIRESTORE_KEY_SEGUNDA_REUNION = 'segunda-reunion';
const FIRESTORE_KEY_NAME = 'name';
const FIRESTORE_KEY_MIN = 'min';
const FIRESTORE_KEY_MAX = 'max';
const FIRESTORE_KEY_OCCUPIED = 'occupied';

export default {
    FIRESTORE_KEY_PRIMERA_REUNION,
    FIRESTORE_KEY_SEGUNDA_REUNION,
    FIRESTORE_KEY_NAME,
    FIRESTORE_KEY_MIN,
    FIRESTORE_KEY_MAX,
    FIRESTORE_KEY_OCCUPIED,
};
