const FIRESTORE_KEY_PRIMERA_REUNION = 'primera-reunion';
const FIRESTORE_KEY_SEGUNDA_REUNION = 'segunda-reunion';
const FIRESTORE_KEY_REUNIONS = 'reunions';
const FIRESTORE_KEY_MAX = 'max';
const FIRESTORE_KEY_MIN = 'min';
const FIRESTORE_KEY_OCCUPIED = 'occupied';
const FIRESTORE_KEY_RESERVED = 'reserved';
const FIRESTORE_KEY_DAY_OF_WEEK = 'reunionDayOfWeek';
const FIRESTORE_KEY_START_TIME = 'startTime';
const FIRESTORE_KEY_END_TIME = 'endTime';

export default {
    FIRESTORE_KEY_PRIMERA_REUNION,
    FIRESTORE_KEY_SEGUNDA_REUNION,
    FIRESTORE_KEY_REUNIONS,
    FIRESTORE_KEY_MAX,
    FIRESTORE_KEY_MIN,
    FIRESTORE_KEY_OCCUPIED,
    FIRESTORE_KEY_RESERVED,
    FIRESTORE_KEY_DAY_OF_WEEK,
    FIRESTORE_KEY_START_TIME,
    FIRESTORE_KEY_END_TIME,
};
